--- Schema-as-code: table definitions as the source of truth for columns.
---
--- ```lua
--- -- schemas/users.lua
--- local schema = require("fredy.schema")
---
--- return schema.table("users", {
---     id    = schema.integer{ primary = true },
---     name  = schema.text{ required = true },
---     age   = schema.integer{},
---     email = schema.text{ unique = true }
--- })
--- ```
---
--- Pass the schema to db:table() and every column reference in the
--- builder (where, select, insert, update, order_by) is validated
--- against it. create_sql() generates the DDL for migrations.

local schema = {}

local function check_identifier(name)
    assert(type(name) == "string" and name:match("^[%a_][%w_]*$"),
           ("invalid SQL identifier: %q"):format(tostring(name)))
    return name
end

---@class fredy.ColumnOptions
---@field primary? boolean
---@field required? boolean   adds NOT NULL
---@field unique? boolean
---@field default? boolean|number|string
---@field references? fredy.Schema  foreign key to that schema's primary key

---@class fredy.Column
---@field kind '"integer"'|'"text"'|'"real"'|'"boolean"'
---@field primary boolean
---@field required boolean
---@field unique boolean
---@field default? boolean|number|string
---@field references? fredy.Schema

local function column(kind)
    ---@param opts? fredy.ColumnOptions
    ---@return fredy.Column
    return function(opts)
        opts = opts or {}
        return {
            kind = kind,
            primary = opts.primary or false,
            required = opts.required or false,
            unique = opts.unique or false,
            default = opts.default,
            references = opts.references
        }
    end
end

schema.integer = column("integer")
schema.text = column("text")
schema.real = column("real")
schema.boolean = column("boolean")

-- boolean maps to integer on SQLite: sqlx's Any driver does not map
-- SQLite's BOOLEAN type (see docs/adr/0001-thin-rust-sqlx.md)
local TYPE_SQL = {
    sqlite = { integer = "integer", text = "text", real = "real", boolean = "integer" },
    postgres = { integer = "integer", text = "text", real = "double precision", boolean = "boolean" }
}

local function default_literal(value, adapter)
    if type(value) == "string" then
        return "'" .. value:gsub("'", "''") .. "'"
    end
    if type(value) == "boolean" then
        if adapter == "sqlite" then return value and "1" or "0" end
        return tostring(value)
    end
    return tostring(value)
end

---@class fredy.Schema
---@field name string
---@field columns table<string, fredy.Column>
---@field primary_key string?
local Table = {}
Table.__index = Table

---@param name string
---@param columns table<string, fredy.Column>
---@return fredy.Schema
function schema.table(name, columns)
    check_identifier(name)
    assert(type(columns) == "table" and next(columns) ~= nil,
           "schema.table requires at least one column")

    local primary_key
    for column_name, definition in pairs(columns) do
        check_identifier(column_name)
        assert(type(definition) == "table" and definition.kind,
               ("column %q must be built with schema.integer{}, schema.text{}, ..."):format(
                   column_name))
        if definition.primary then
            assert(not primary_key,
                   ("schema %q has more than one primary key"):format(name))
            primary_key = column_name
        end
    end

    return setmetatable({
        name = name,
        columns = columns,
        primary_key = primary_key
    }, Table)
end

---@param column_name string
---@return boolean
function Table:has_column(column_name)
    return self.columns[column_name] ~= nil
end

--- Ordered deterministically: primary key first, the rest alphabetical.
function Table:column_order()
    local names = {}
    for column_name in pairs(self.columns) do
        if column_name ~= self.primary_key then table.insert(names, column_name) end
    end
    table.sort(names)
    if self.primary_key then table.insert(names, 1, self.primary_key) end
    return names
end

--- Generates the CREATE TABLE statement for the adapter.
---@param adapter '"postgres"'|'"sqlite"'
---@return string
function Table:create_sql(adapter)
    local types = TYPE_SQL[adapter]
    assert(types, ("unknown adapter %q"):format(tostring(adapter)))

    local defs = {}
    for _, column_name in ipairs(self:column_order()) do
        local definition = assert(self.columns[column_name])
        local parts = { '"' .. column_name .. '"' }

        if definition.primary and definition.kind == "integer" then
            if adapter == "postgres" then
                table.insert(parts, "integer generated by default as identity primary key")
            else
                table.insert(parts, "integer primary key")
            end
        else
            table.insert(parts, types[definition.kind])
            if definition.primary then table.insert(parts, "primary key") end
            if definition.required then table.insert(parts, "not null") end
            if definition.unique then table.insert(parts, "unique") end
            if definition.default ~= nil then
                table.insert(parts, "default " .. default_literal(definition.default, adapter))
            end
            if definition.references then
                local target = definition.references
                assert(target.primary_key,
                       ("schema %q referenced by %q has no primary key"):format(
                           target.name, column_name))
                table.insert(parts, ('references "%s" ("%s")'):format(
                                 target.name, target.primary_key))
            end
        end

        table.insert(defs, table.concat(parts, " "))
    end

    return ('create table "%s" (%s)'):format(self.name, table.concat(defs, ", "))
end

return schema
