local schema = require("fredy.schema")
local migrations = require("fredy.migrations")
local helper = require("spec.helper")

local function users_schema()
    return schema.table("users", {
        id = schema.integer({ primary = true }),
        name = schema.text({ required = true }),
        age = schema.integer({}),
        vip = schema.boolean({ default = false }),
    })
end

describe("schema definition", function()
    it("captures name, columns and primary key", function()
        local users = users_schema()

        assert.are.equal("users", users.name)
        assert.are.equal("id", users.primary_key)
        assert.is_true(users:has_column("age"))
        assert.is_false(users:has_column("aeg"))
    end)

    it("orders columns deterministically: pk first, rest alphabetical", function()
        assert.are.same({ "id", "age", "name", "vip" }, users_schema():column_order())
    end)

    it("rejects two primary keys", function()
        assert.error_matches(function()
            schema.table("bad", {
                a = schema.integer({ primary = true }),
                b = schema.integer({ primary = true }),
            })
        end, "more than one primary key")
    end)

    it("rejects invalid identifiers and raw column defs", function()
        assert.error_matches(function()
            schema.table("users; drop", { id = schema.integer({}) })
        end, "invalid SQL identifier")

        assert.error_matches(function()
            ---@diagnostic disable-next-line: assign-type-mismatch
            schema.table("users", { id = "integer" })
        end, "must be built with")
    end)
end)

describe("schema create_sql", function()
    it("generates sqlite DDL (boolean becomes integer)", function()
        local sql = users_schema():create_sql("sqlite")

        assert.are.equal(
            'create table "users" ("id" integer primary key, '
                .. '"age" integer, "name" text not null, "vip" integer default 0)',
            sql
        )
    end)

    it("generates postgres DDL with identity and real boolean", function()
        local sql = users_schema():create_sql("postgres")

        assert.are.equal(
            'create table "users" '
                .. '("id" integer generated by default as identity primary key, '
                .. '"age" integer, "name" text not null, "vip" boolean default false)',
            sql
        )
    end)

    it("generates foreign keys from references", function()
        local users = users_schema()
        local posts = schema.table("posts", {
            id = schema.integer({ primary = true }),
            user_id = schema.integer({ required = true, references = users }),
        })

        assert.are.equal(
            'create table "posts" ("id" integer primary key, '
                .. '"user_id" integer not null references "users" ("id"))',
            posts:create_sql("sqlite")
        )
    end)

    it("escapes quotes in string defaults", function()
        local t = schema.table("notes", {
            id = schema.integer({ primary = true }),
            body = schema.text({ default = "it's fine" }),
        })

        assert.error_matches(function()
            ---@diagnostic disable-next-line: param-type-mismatch
            t:create_sql("mongo")
        end, "unknown adapter")
        assert.matches("default 'it''s fine'", t:create_sql("sqlite"), 1, true)
    end)
end)

describe("schema-aware builder", function()
    local db, users

    before_each(function()
        db = helper.open_db()
        users = users_schema()
        db:execute(users:create_sql("sqlite"))
    end)

    after_each(function()
        db:close()
    end)

    it("accepts a schema in db:table and works end to end", function()
        db:table(users):insert({ name = "ana", age = 28 })

        local row = db:table(users):where("age", ">=", 18):first()

        assert.are.equal("ana", row.name)
        assert.are.equal(0, row.vip) -- default applied
    end)

    it("rejects unknown columns everywhere", function()
        local cases = {
            function()
                db:table(users):where("aeg", 1)
            end,
            function()
                db:table(users):where({ aeg = 1 })
            end,
            function()
                db:table(users):order_by("aeg")
            end,
            function()
                db:table(users):select({ "aeg" })
            end,
            function()
                db:table(users):insert({ aeg = 1 })
            end,
            function()
                db:table(users):update({ aeg = 1 })
            end,
        }

        for _, case in ipairs(cases) do
            assert.error_matches(case, 'column "aeg" does not exist in schema "users"')
        end
    end)

    it("plain string tables keep working without validation", function()
        db:execute("create table free (anything integer)")
        db:table("free"):insert({ anything = 1 })

        assert.are.equal(1, db:table("free"):count())
    end)
end)

describe("schema + migrations", function()
    it("create_sql plugs into migrations.run", function()
        local db = helper.open_db()
        local users = users_schema()

        migrations.run(db, {
            { name = "0001_create_users", up = users:create_sql(db:adapter()) },
        })

        db:table(users):insert({ name = "ana" })
        assert.are.equal(1, db:table(users):count())
        db:close()
    end)
end)
